### ISSUE TITLE
Guide Issue for Mata / Essential Phone - Instructions Have Error

### ISSUE THREAD

**Issue by hatoncat** [TeamWin/Team-Win-Recovery-Project#1536]
- [X] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [X] I am running the latest version of TWRP
- [X] I have read the FAQ (https://twrp.me/FAQ/)
- [X] I have searched for my issue and it does not already exist

**Device codename**: Mata
**TWRP version**: 3.2.3.0 (Current for Mata)

#### WHAT STEPS WILL REPRODUCE THE PROBLEM?
The steps to install on mata are incorrect. I have submitted this issue via Contact Us and here since it is not a code issue, but a guide issue.

#### WHAT IS THE EXPECTED RESULT?
The installation guide should work properly. 

#### WHAT HAPPENS INSTEAD?
There is a bug in the steps blocking booting of the twrp initial image.

#### ADDITIONAL INFORMATION
**Part 0:** You currently must use a USB mouse with the Type-C port at the bottom of the device. The platform is much more stable with Android 10 firmware, but only Pie Release 1 and earlier for the device allow the touchscreen to work with current/official builds.

**Part 1:** As of Android 10, the boot slots are have changed. Slot _a and slot _b are now just "a" and "b" - this needs to be updated because set_active for _a and _b will now fail.

**Part 2:** The step that reads _"fastboot flash boot <recovery_filename>.img"_

Is incorrect.

You actually need to type _"fastboot flash **boot_x** <recovery_filename>.img"_ 

**Where "x" represents the A or B slot you want to boot to, in lower case.**

**Also important: You do still need to set-active the boot slot you want to boot to first. You cannot remove/skip that prior step just because boot_x is specified. If you do not set it active first, and then boot_x the same slot, the flash will fail.**

This is confirmed on the LineageOS [instructions guides for mata](https://wiki.lineageos.org/devices/mata/install), and LineageOS believes it is a bug/quirk with Essential Phone.

Confirmed just now on my own Essential Phone, flashing TWRP for the first time. After this change, it works properly.
